### ISSUE TITLE
Django extensions incompatibility  

### ISSUE THREAD

**Issue by shiriru** [beaugunderson/django-gulp#4]
Hello,

I'm using extensively django-extensions for development, and especially `./manage.py runserver_plus` command, that allows me to make posrmortem debugging, which for me is essential. However, I cannot get django-gulp to initiate my `gulpfile.js` with `runserver_plus`. In runs correctly with Django's simple `runserver`, though.

Is there any workaround to use django-gulp with django-extenstions?

**Comment by beaugunderson** [comment]
I use django-extensions but not the `runserver_plus` extension. I think that it will be possible to override `runserver_plus` as well.

**Comment by beaugunderson** [comment]
Hm, that was easy enough but my regular `runserver_plus` seems broken (it seems to launch two runserver processes; I'm not sure why).

Can you try [this branch](https://github.com/beaugunderson/django-gulp/tree/runserver-plus)?

**Comment by shiriru** [comment]
I confirm it runs for me with `runserver-plus` branch. It complains about the second runserver process, however does the job, which at the end is most important :)  

> Hm, that was easy enough but my regular `runserver_plus` seems broken (it seems to launch two runserver processes; I'm not sure why).

It's not broken - that's the normal behavior. I believe it has something to do with `ipdb` trace injection on the fly.

**Comment by jonesnc** [comment]
@shiriru I can also confirm that the `runserver-plus` branch appears to work, although I'm also seeing two runserver processes.

@beaugunderson any chance of the `runserver-plus` branch getting merged soon?

**Comment by beaugunderson** [comment]
this is now merged and available in 4.1.0; sorry for the delay!
