### ISSUE TITLE
Fail collectstatic if gulp fails

### ISSUE THREAD

**Issue by joshblum** [beaugunderson/django-gulp#6]
It would be helpful if the gulp process fails that the collectstatic command also fails. Right now the exit code is unused at https://github.com/beaugunderson/django-gulp/blob/master/django_gulp/management/commands/collectstatic.py#L36 so it should be simple to fail the command here. I can submit a PR if you think this will be useful! Let me know :)

**Comment by beaugunderson** [comment]
sounds great, will happily merge a PR for that, thank you!

---

**Comment by joshblum** [comment]
Great! If the PR ( #7 ) looks ok, could you update the pypi version? It would be great if I could use this fix in my code asap. Thanks!!

**Comment by beaugunderson** [comment]
merged #7 and released as 2.4.1, thanks again!

**Comment by joshblum** [comment]
Thank you so much for the speedy responses!!
