### ISSUE TITLE
Doesn't work with ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by knyghty** [beaugunderson/django-gulp#8]
Didn't test any other storage backends.

Would be nice if this was supported, but if it's not going to happen it would also be nice to document that it doesn't work, and perhaps suggest an alternative.

**Comment by beaugunderson** [comment]
will look at what it takes to support this; if you beat me to it I'd also to be happy to merge a PR :)

---

**Comment by knyghty** [comment]
I don't now much about Gulp (we were already using it when I joined), but I can give you a bit of a (not very closely investigated) lead at least.

Seems that `collectstatic` correctly creates the manifest file and creates the files with the hashed filenames.

Where it seems to fail is that in templates, something appears to be rewriting the static URLs (I didn't look into this much), adding things like `integrity` attributes, and this (I guess) is overriding `{% static %}`'s behaviour and not using the files with hashes.

**Comment by beaugunderson** [comment]
hmm, weird! what other Django modules are you using in your `INSTALLED_APPS`?

fwiw I use this in production and it does work with `django-gulp`:

```
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```

**Comment by beaugunderson** [comment]
looked at the Django source and don't see `integrity` attributes anywhere there...

**Comment by beaugunderson** [comment]
I switched my local instance to `django.contrib.staticfiles.storage.ManifestStaticFilesStorage`, ran `collectstatic`, and everything still worked--some additional information about your app would help in diagnosing this :)

**Comment by knyghty** [comment]
I'm going to assume it's something weird we're doing then and close this unless I can find something more useful to go on
