### ISSUE TITLE
Install futures only in python2

### ISSUE THREAD

**Issue by jorrete** [beaugunderson/django-gulp#9]
Hi,

I'm using django-gulp in python 3. 

It works well but I'm having some interaction-problems.

django-pipeline imports 'concurrent.future' and in some cases  'futures' raises a exception in python2 way that it is not supported in python3 (two exceptions without brackets).

django-gulp gave me no problem with python3 but the fact that 'futures' is also installed in python3 makes some packages use the installed 'futures' instead of the standard library.

It would be nice to make the 'futures' i[nstallation depending on the python version](http://stackoverflow.com/questions/21082091/install-requires-based-on-python-version).

Thanks.

**Comment by beaugunderson** [comment]
good catch! i'll implement that :)

---

**Comment by beaugunderson** [comment]
hey @jorrete--sorry this took two years but this is fixed in 4.0.1!
